---
--- Generated by EmmyLua(https://github.com/EmmyLua) in IntelliJ IDEA
--- Created by Will.
--- DateTime: 4/27/2021 9:21 PM
---

-- Map multi-dimension tables to single dimension kvp table
function map(table, f)
    local t = {}

    for key, value in pairs(table) do
        if value ~= nil and type(value) == 'table' then
            t[value.label or key] = f(value)
        end
    end

    return t
end
