---
--- Generated by EmmyLua(https://github.com/EmmyLua) in IntelliJ IDEA
--- Created by WIll.
--- DateTime: 5/16/2021 8:23 PM
---
local component = require('component')
local term = require('term')

local gpu = component.gpu
--               ERROR      WAIT    CRAFTING    QUEUE
local colors = {0xFB4B4B, 0xFEFF5C, 0x32CD32, 0x2FEAE5}

function updateUI(manager)
    term.setCursor(1,1)

    gpu.setBackground(0x000000)
    gpu.fill(1, 1, 109, 40, " ")

    if not manager:hasJobs() then
        gpu.setResolution(4,5)
        gpu.setForeground(0x32CD32)

        term.setCursor(1, 3)
        term.write("IDLE");
    else
        gpu.setResolution(109,40)
        gpu.setForeground(0x555555)
        local limit = 0
        for key, value in pairs(manager.status) do
            if limit > 9 then
                break
            end

            local col, row = term.getCursor()

            local status = colors[getStatus(value[2])]
            local item = key
            local amount = value[1]

            drawBackground(status, col, row)
            populateBox(item, amount, col, row)

            if col < 70 then
                term.setCursor(col+37, row)
            else
                term.setCursor(1, row+11)
            end

            limit = limit + 1
        end
    end

    term.setCursor(1,1)
end

function getStatus(statusCode)
    if statusCode == "QUEUE" then
        return 4
    end

    if statusCode == "WAIT" then
        return 2
    end

    if statusCode == "ERROR" then
        return 1
    end

    if statusCode == "CRAFTING" then
        return 3
    end
end

function populateBox(item, amount, col, row)
    term.setCursor(col+9, row+3)
    term.write(item)

    term.setCursor(col+15, row+6)
    term.write(amount)

    term.setCursor(col, row)
end

function drawBackground(status, col, row)
    gpu.setBackground(status)

    gpu.fill(col, row, 35, 10, " ")
end
